#include <string>
#include <unordered_map>

namespace alicia
{
  const std::unordered_map<uint32_t, std::string_view>& GetMessages();
  std::string_view GetMessageName(uint32_t id);
}

#define LITERAL(string) #string

#if ALICIA_PROTOCOL == 1
#define AcCmdCLRequestLeagueInfo 0x376
#define AcCmdCLPCInfoLog 0x46c
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_796 0x31c
#define AcCmdCLGuildPartyList 0x3c2
#define AcCmdCLEnterGuildParty 0x3c4
#define AcCmdCLStartGuildPartyMatch 0x3d0
#define AcCmdCLStopGuildPartyMatch 0x3d6
#define AcCmdCLLeaveGuildParty 0x3cb
#define AcCmdCRRequestGuildMatchInfo 0x408
#define AcCmdCRRequestGuildRankingInfoList 0x420
#define AcCmdCLChangeGuildPartyOptions 0x410
#define AcCmdCLMakeGuildParty 0x3bc
#define AcCmdCRRequestGuildRankingInfo 0x41d
#define AcCmdCRWearEquipment 0x81
#define AcCmdCRPasswordAuth 0x300
#define AcCmdCRUserPetInfos 0x3e2
#define AcCmdCRIncubateEgg 0x39f
#define AcCmdCRBoostIncubateEgg 0x3a9
#define AcCmdCRBoostIncubateInfoList 0x3b3
#define AcCmdCRBoostIncubateEggOther 0x3ae
#define AcCmdCRAcceptBoostIncubateEgg 0x3b7
#define AcCmdCRPetBornResult 0x3a4
#define AcCmdCRHousingBuild 0x25b
#define AcCmdCRUpdatePet 0x390
#define AcCmdCRRequestPetBirth 0x39a
#define AcCmdCRUpdateDailyQuest 0x344
#define AcCmdCRRequestDailyQuestReward 0x350
#define AcCmdCRRegisterQuest 0x3e6
#define AcCmdCRGiveupQuest 0x3ec
#define AcCmdCRRequestQuestReward 0x3f2
#define AcCmdCRRegisterDailyQuestGroup 0x33e
#define AcCmdCRChangeAge 0x45e
#define AcCmdCRHideAge 0x465
#define AcCmdCRRequestSystemParam 0x368
#define AcCmdCRRequestLeagueReward 0x382
#define AcCmdCLInquiryTreecash 0x2b1
#define AcCmdCRChangeNickname 0x2f9
#define AcCmdCRUnregisterStallionEstimateInfo 0x296
#define AcCmdCRUnregisterStallion 0x14b
#define AcCmdCRPasswordAuthOK 0x301
#define AcCmdCRPasswordAuthCancel 0x302
#define AcCmdCLLoginCancel 0x9
#define AcCmdCLMakeRoomOK 0x14
#define AcCmdCLMakeRoomCancel 0x15
#define AcCmdCLEnterRoomOK 0x1d
#define AcCmdCLEnterRoomCancel 0x1e
#define AcCmdCLLeaveRoomOK 0x26
#define AcCmdCLEnterChannelOK 0x2c
#define AcCmdCLEnterChannelCancel 0x2d
#define AcCmdCLLeaveChannelOK 0x2f
#define AcCmdCLDisconnectClientsNotify 0x170
#define AcCmdCLCreateNicknameNotify 0x6b
#define AcCmdCLCreateNicknameCancel 0x6e
#define AcCmdCLShowInventoryCancel 0x80
#define AcCmdCLUpdateUserSettingsOK 0x91
#define AcCmdCLUpdateUserSettingsCancel 0x92
#define AcCmdCLEnterRoomQuickCancel 0x96
#define AcCmdCLGoodsShopListOK 0xb3
#define AcCmdCLGoodsShopListCancel 0xb4
#define AcCmdLCAchievementRewardNotify 0xee
#define AcCmdCLEnterRanchOK 0xfd
#define AcCmdCLEnterRanchCancel 0xfe
#define AcCmdCLLeaveRanchOK 0x100
#define AcCmdCLLeaveRanchCancel 0x101
#define AcCmdLCMessengerCommandInvocation 0xe06
#define AcCmdLCGameguardCheckQuery 0x122
#define AcCmdLCGameguardEventNotify 0x124
#define AcCmdCLAchievementCompleteOK 0x168
#define AcCmdCLAchievementCompleteCancel 0x169
#define AcCmdCLGetMessengerInfoOK 0x187
#define AcCmdCLGetMessengerInfoCancel 0x188
#define AcCmdCLCheckWaitingSeqnoOK 0x1bc
#define AcCmdCLEnterRoomQuickStopOK 0x1f2
#define AcCmdCLEnterRoomQuickStopCancel 0x1f3
#define AcCmdCLRequestFestivalPrizeOK 0x1fd
#define AcCmdCLRequestFestivalPrizeCancel 0x1fe
#define AcCmdCLEnterRoomQuickSuccess 0x204
#define AcCmdCLEnterGuildPartyCancel 0x3c6
#define AcCmdCLLeaveGuildPartyOK 0x3cc
#define AcCmdCLLeaveGuildPartyNotify 0x3cd
#define AcCmdCLStartGuildPartyMatchOK 0x3d1
#define AcCmdCLStartGuildPartyMatchCancel 0x3d2
#define AcCmdCLStopGuildPartyMatchOK 0x3d7
#define AcCmdCLStopGuildPartyMatchCancel 0x3d8
#define AcCmdLCGuildPartyMatchFound 0x3dd
#define AcCmdLCGuildMatchAvailable 0x40f
#define AcCmdCLChangeGuildPartyOptionsCancel 0x412
#define AcCmdCLQueryServerTimeOK 0x26b
#define AcCmdLCMissionRecordUpdate 0x107
#define AcCmdLCOpKick 0x292
#define AcCmdLCHackShieldRequest 0x293
#define AcCmdLCHackShieldResult 0x295
#define AcCmdLCGoodsShopListData 0x2b0
#define AcCmdCLInquiryTreecashOK 0x2b2
#define AcCmdCLInquiryTreecashCancel 0x2b3
#define AcCmdLCAlertGiftbox 0x29d
#define AcCmdLCPTSPremiumInfo 0x317
#define AcCmdLCOpMute 0x33c
#define AcCmdCLRequestLeagueInfoCancel 0x378
#define AcCmdCLCheckAccountDBAuthOK 0x193
#define AcCmdCLCheckAccountDBAuthCancel 0x194
#define AcCmdCLHeartbeat 0x12
#define AcCmdCLCheckWaitingSeqno 0x1bb
#define AcCmdCLEnterChannel 0x2b
#define AcCmdCLLeaveChannel 0x2e
#define AcCmdCLRoomList 0x10
#define AcCmdCLLeaveRoom 0x25
#define AcCmdCLChangeRanchOptionOK 0x30e
#define AcCmdCLChangeRanchOptionCancel 0x30f
#define AcCmdCLRequestLeagueInfoOK 0x377
#define AcCmdCLCreateNickname 0x6c
#define AcCmdLCNotice 0x39
#define AcCmdCLEnterGuildPartyNotify 0x3c7
#define AcCmdCLRequestDailyQuestListOK 0x357
#define AcCmdCLRequestQuestListOK 0x3f9
#define AcCmdCLRequestSpecialEventListOK 0x418
#define AcCmdCLEnterRoom 0x1c
#define AcCmdCLFeatureCommand 0x118
#define AcCmdCRAchievementUpdateProperty 0x16b
#define AcCmdCLLogin 0x7
#define AcCmdCLAchievementCompleteListOK 0xe6
#define AcCmdLCUpdateSystemContent 0x1c1
#define AcCmdLCBreedingNoticeNotify 0x203
#define AcCmdCLChangeGuildPartyOptionsOK 0x411
#define AcCmdCLChangeGuildPartyOptionsNotify 0x413
#define AcCmdLCInviteGuildJoin 0x2d2
#define AcCmdCLRequestMountInfoOK 0x276
#define AcCmdCLLoginOK 0x8
#define AcCmdLCPersonalInfo 0xec
#define AcCmdLCSkillCardPresetList 0x235
#define AcCmdCLEnterGuildPartyOK 0x3c5
#define AcCmdCLRoomListOK 0x11
#define AcCmdCLShowInventoryOK 0x7f
#define AcCmdCLRequestFestivalResultOK 0x166
#define AcCmdCLGuildPartyListOK 0x3c3
#define AcCmdRCLeaveRoom 0x30b
#define AcCmdRCAddSkillEffect 0xa6
#define AcCmdRCMobMove 0xbe
#define AcCmdCRUpdateRanchLevelNotify 0x269
#define AcCmdCRRelay 0x2f7
#define AcCmdCRReadyRaceNotify 0x59
#define AcCmdCRStartRaceCancel 0x5c
#define AcCmdCRChangeMasterNotify 0x5d
#define AcCmdUserRaceTimerOK 0x1025
#define AcCmdBrokerTest 0x108e
#define AcCmdUserRaceCountdown 0x102d
#define AcCmdUserRaceDeleteNotify 0x1036
#define AcCmdGameRaceItemSpawn 0x1045
#define AcCmdGameRaceItemGet 0x1048
#define AcCmdGameQuestItemSpawn 0x104b
#define AcCmdGameQuestItemGet 0x104c
#define AcCmdUserRaceFinalNotify 0x1037
#define AcCmdCREnterRoomCancel 0x33
#define AcCmdCRLeaveRoomNotify 0x35
#define AcCmdCRLeaveRoomOK 0x36
#define AcCmdRCNPCSpawn 0x4a
#define AcCmdCRAttackNPCNotify 0x4c
#define AcCmdCRNPCAttachNotify 0x50
#define AcCmdRCNPCDestroyed 0x51
#define AcCmdCRKickNotify 0x5f
#define AcCmdCRChangeTeamOK 0x8b
#define AcCmdCRChangeTeamCancel 0x8c
#define AcCmdCRChangeTeamNotify 0x8d
#define AcCmdCRRequestItemOK 0x94
#define AcCmdCRRequestMagicItemOK 0xb6
#define AcCmdCRRequestMagicItemNotify 0xb7
#define AcCmdRCRagePointNotify 0x11c
#define AcCmdCRStarPointGetOK 0x9c
#define AcCmdCRUseItemSlotCancel 0xa4
#define AcCmdCRUseMagicItemCancel 0xba
#define AcCmdRCRevengeTargetNotify 0x120
#define AcCmdRCRemoveSkillEffect 0xa7
#define AcCmdCRChangeUserSlotOK 0xab
#define AcCmdCRChangeUserSlotCancel 0xac
#define AcCmdCRChangeUserSlotNotify 0xad
#define AcCmdRCAddMonster 0xae
#define AcCmdRCBindMonster 0xaf
#define AcCmdCRAttackMonsterNotify 0x64
#define AcCmdRCTeamSpurGauge 0xbc
#define AcCmdRCMobTrace 0xbf
#define AcCmdRCMobLookAt 0xc0
#define AcCmdRCMobSetScale 0xc1
#define AcCmdRCMobSetState 0xc2
#define AcCmdRCMobSetHP 0xc3
#define AcCmdRCMobDetachPart 0xc4
#define AcCmdRCMobSetMoveType 0xc5
#define AcCmdRCMobDead 0xc6
#define AcCmdRCMobUseSkillToGround 0xc7
#define AcCmdRCMobUseSkillToObject 0xc8
#define AcCmdRCMobMovingAttack 0x11a
#define AcCmdRCMobLead 0xcb
#define AcCmdRCMobSetHPBySkill 0xcc
#define AcCmdRCActivateLevelDevice 0xce
#define AcCmdRCActivateLevelDeviceTrigger 0xcf
#define AcCmdRCDeactivateLevelDeviceTrigger 0xd0
#define AcCmdRCMobPlayerDamaged 0xd3
#define AcCmdRCMobPlayerSkillDamaged 0xd4
#define AcCmdRCMobEndGame 0xd5
#define AcCmdCRMobAttackMobNotify 0xd6
#define AcCmdCRMobSkillToMobNotify 0xd7
#define AcCmdRCMobPlayerStatus 0xda
#define AcCmdRCMobPlayerSetHP 0xdb
#define AcCmdRCMobSetHPMax 0xdd
#define AcCmdRCMobStop 0xde
#define AcCmdRCMobResetPos 0xdf
#define AcCmdRCMissionEvent 0xe0
#define AcCmdRCLevelDeviceAction 0xea
#define AcCmdRCCreateItem 0xe1
#define AcCmdRCMobKnockback 0xf1
#define AcCmdRCMobSetVelocity 0xf2
#define AcCmdRCCreateObstacle 0xf3
#define AcCmdRCMobAttachPart 0xf4
#define AcCmdRCMobRemoveStatus 0xf5
#define AcCmdRCMobTargetingOn 0xf6
#define AcCmdRCMobTargetingOff 0xf7
#define AcCmdRCMobUnlink 0xf9
#define AcCmdRCMobGazeAt 0xfa
#define AcCmdRCMobPlayerSetMP 0xfb
#define AcCmdRCMobPlayerDead 0x105
#define AcCmdRCMobRun 0x108
#define AcCmdRCMobThrust 0x10c
#define AcCmdRCMobPlayerReflectSkill 0xd9
#define AcCmdRCMobSetDefaultState 0x117
#define AcCmdRCAlert 0x11d
#define AcCmdCRHurdleClearResultOK 0xe8
#define AcCmdCRRequestSpurOK 0x9a
#define AcCmdUserRaceCloseWait 0x1030
#define AcCmdRCAchievementCompleteNotify 0x17c
#define AcCmdRCKickFromRace 0x185
#define AcCmdCRAwardEndNotify 0x1b5
#define AcCmdRCAwardNotify 0x195
#define AcCmdRCAwardEnd 0x196
#define AcCmdRCTriggerActivate 0x1a5
#define AcCmdCRTriggerizeAct 0x283
#define AcCmdCRLoadingCompleteNotify 0x1b7
#define AcCmdRCChangeAIOwner 0x1c7
#define AcCmdRCRoomCountdown 0x1df
#define AcCmdRCFestivalMissionReport 0x1fb
#define AcCmdCRRaceResultOK 0x20a
#define AcCmdCRRaceResultCancel 0x20b
#define AcCmdRCRoomCountdownCancel 0x20c
#define AcCmdRCResetPos 0x215
#define AcCmdRCUpdateGameMoney 0x234
#define AcCmdCRMountFamilyTreeCancel 0x21f
#define AcCmdRCGuildModeStar 0x242
#define AcCmdCRAchievementDetailCancel 0x246
#define AcCmdCRSetKeyAchievementOK 0x176
#define AcCmdCRSetKeyAchievementCancel 0x177
#define AcCmdCRMountInjuryHealOK 0x24c
#define AcCmdCRMountInjuryHealCancel 0x24d
#define AcCmdCREmblemListCancel 0x253
#define AcCmdCRSetKeyEmblemOK 0x255
#define AcCmdCRSetKeyEmblemCancel 0x256
#define AcCmdCRSetKeyEmblemNotify 0x257
#define AcCmdRCAchievementUpdateNotify 0xe4
#define AcCmdCRCreateGuildOK 0x2bf
#define AcCmdCRCreateGuildCancel 0x2c0
#define AcCmdCRWithdrawGuildMemberOK 0x2c5
#define AcCmdCRWithdrawGuildMemberCancel 0x2c6
#define AcCmdCRGuildMemberListCancel 0x2d8
#define AcCmdCRUpdateGuildMemberGradeOK 0x2dd
#define AcCmdCRUpdateGuildMemberGradeCancel 0x2de
#define AcCmdCRRequestGuildInfoCancel 0x2e4
#define AcCmdRCWithdrawGuildMemberNotify 0x2ee
#define AcCmdRCUpdateGuildMemberGradeNotify 0x2f0
#define AcCmdRCModifyGuildEmblemNotify 0x2f4
#define AcCmdCRRelayCommandNotify 0x2f6
#define AcCmdCRUseItemOK 0x1e1
#define AcCmdCRUseItemCancel 0x1e2
#define AcCmdRCMagicExpire 0x313
#define AcCmdRCMountRentExpire 0x32b
#define AcCmdCRRegisterDailyQuestGroupOK 0x33f
#define AcCmdCRRegisterDailyQuestGroupCancel 0x340
#define AcCmdCRUpdateDailyQuestOK 0x345
#define AcCmdCRUpdateDailyQuestCancel 0x346
#define AcCmdCRGiveupDailyQuestOK 0x34b
#define AcCmdCRGiveupDailyQuestCancel 0x34c
#define AcCmdRCUpdateDailyQuestNotify 0x35c
#define AcCmdRCCompleteDailyQuestNotify 0x35d
#define AcCmdCRRegisterQuestOK 0x3e7
#define AcCmdCRRegisterQuestCancel 0x3e8
#define AcCmdCRGiveupQuestOK 0x3ed
#define AcCmdCRGiveupQuestCancel 0x3ee
#define AcCmdRCUpdateQuestNotify 0x3fe
#define AcCmdRCUpdateLeagueScoreNotify 0x372
#define AcCmdRCUpdateLeagueGradeNotify 0x375
#define AcCmdCRRequestLeagueTeamListCancel 0x37e
#define AcCmdRCTimeoutCareUser 0x393
#define AcCmdRCGameCreateClientItem 0x398
#define AcCmdRCObtainEgg 0x39e
#define AcCmdRCGuildRaceInfo 0x404
#define AcCmdRCGuildRaceResult 0x406
#define AcCmdCRRequestGuildMatchInfoCancel 0x40a
#define AcCmdCRRequestGuildRankingInfoCancel 0x41f
#define AcCmdCRRequestGuildRankingInfoListCancel 0x422
#define AcCmdRCObstacleStatus 0x452
#define AcCmdCRChangeAgeOK 0x45f
#define AcCmdCRChangeAgeCancel 0x460
#define AcCmdCRHideAgeOK 0x466
#define AcCmdCRChangeMagicTarget 0x22c
#define AcCmdCRSkillSystemEvent 0x23a
#define AcCmdCREnterRoom 0x30
#define AcCmdUserRaceTimer 0x1024
#define AcCmdCRHeartbeat 0x9e
#define AcCmdCRLoadingComplete 0x1b6
#define AcCmdCRTriggerLevelDevice 0xcd
#define AcCmdUserRaceItemGet 0x10a3
#define AcCmdCRNPCAttach 0x4f
#define AcCmdCRKick 0x5e
#define AcCmdCRReadyRace 0x58
#define AcCmdCRChangeMagicTargetOK 0x22d
#define AcCmdCRChangeMagicTargetCancel 0x22e
#define AcCmdCRChangeMagicTargetNotify 0x22f
#define AcCmdRCRemoveMagicTarget 0x231
#define AcCmdRCSkillSystemEvent 0x241
#define AcCmdCRAchievementDetailOK 0x245
#define AcCmdCRRelayNotify 0x2f8
#define AcCmdRCRequestLeagueWeeklyInfoNotify 0x38f
#define AcCmdCRUseMagicItemOK 0xb9
#define AcCmdCRUseMagicItemNotify 0xbb
#define AcCmdGameRaceClientUDPInfo 0x109d
#define AcCmdGameRaceP2PResult 0x109f
#define AcCmdCRUseItemSlotOK 0xa3
#define AcCmdCRUseItemSlotNotify 0xa5
#define AcCmdCRInviteGuildJoinCancel 0x2cc
#define AcCmdRCAcceptGuildJoinNotify 0x2f2
#define AcCmdCRAttackNPC 0x4b
#define AcCmdCRStartRace 0x5a
#define AcCmdServerStatsBase 0x304
#define AcCmdCRChatNotify 0x53
#define AcCmdCRWhisperNotify 0x61
#define AcCmdRCMobAddMob 0xbd
#define AcCmdRCMobSetKey 0xc9
#define AcCmdRCMobClearKey 0xca
#define AcCmdRCUpdateMountInfoNotify 0x1e7
#define AcCmdCRServerStatsNotify 0x307
#define AcCmdCRRequestUserOK 0x35f
#define AcCmdCRRequestUserCancel 0x360
#define AcCmdRCRequestUser 0x367
#define AcCmdCRInviteUserOK 0x36e
#define AcCmdCRInviteUserCancel 0x36f
#define AcCmdCRChat 0x52
#define AcCmdCRChangeRoomOptionsNotify 0x55
#define AcCmdCRUpdateEquipmentNotify 0x14e
#define AcCmdCROpCmdOK 0x28f
#define AcCmdRCMobLinkTo 0xf8
#define AcCmdRCDebugMessage 0x24a
#define AcCmdCREmblemListOK 0x252
#define AcCmdRCSupplyItemInsert 0x286
#define AcCmdCRRequestGuildInfoOK 0x2e3
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_794 0x31a
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_795 0x31b
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_797 0x31d
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_798 0x31e
#define AcCmdRCExchangeItem 0x397
#define AcCmdRCUpdatePet 0x392
#define AcCmdCRRequestGuildMatchInfoOK 0x409
#define AcCmdCRRequestGuildRankingInfoOK 0x41e
#define AcCmdRCUpdateMountAppearanceNotify 0x1d3
#define AcCmdRCResetItemWeekly 0x436
#define AcCmdCRChangeRoomOptions 0x54
#define AcCmdCREnterRoomNotify 0x31
#define AcCmdCRStartRaceNotify 0x5b
#define AcCmdRCUpdateSpecialEventNotify 0x41c
#define AcCmdCRGuildMemberListOK 0x2d7
#define AcCmdCRRequestLeagueTeamListOK 0x37d
#define AcCmdCREnterRoomOK 0x32
#define AcCmdCRMountFamilyTreeOK 0x21e
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumStringValueChanged_int_20_874 0x36a
#define AcCmdCRUserPetInfosOK 0x3e5
#define AcCmdCRRequestGuildRankingInfoListOK 0x421
#define AcCmdRCRaceResultNotify 0x1c3
#define AcCmdCRMountInjuryPlayEvent 0x243
#define AcCmdCRRequestStorage 0x299
#define AcCmdCREmblemList 0x251
#define AcCmdCRChangeSkillCardPresetID 0x237
#define AcCmdCRUseItem 0x1e0
#define AcCmdCRBreedingWishlist 0x1e8
#define AcCmdCREnterBreedingMarket 0x13f
#define AcCmdCRBreedingWishlistAdd 0x1eb
#define AcCmdCRBreedingWishlistDel 0x1ee
#define AcCmdCRMountFamilyTree 0x21d
#define AcCmdCRTryBreeding 0x156
#define AcCmdCRLeaveBreedingMarket 0x142
#define AcCmdCRBreedingFailureCard 0x20f
#define AcCmdCRSearchStallion 0x145
#define AcCmdCRBreedingFailureCardChoose 0x212
#define AcCmdCRActivateSkillEffect 0xa8
#define AcCmdCRRequestMagicItem 0xb5
#define AcCmdCRAwardStart 0x19d
#define AcCmdCRAwardEnd 0x17b
#define AcCmdCRRaceResult 0x69
#define AcCmdUserRaceP2PResult 0x109e
#define AcCmdCRMobActivateSkillEffect 0x425
#define AcCmdCRUseMagicItem 0xb8
#define AcCmdCRStartMagicTarget 0x232
#define AcCmdCROpCmd 0x28e
#define AcCmdCRCheckPCBangGiftItem 0x42d
#define AcCmdCRRequestPCBangGift 0x427
#define AcCmdCRHousingRepair 0x262
#define AcCmdCRSetKeyEmblem 0x254
#define AcCmdCRCheckStorageItem 0x2b7
#define AcCmdCRPurchaseWithdrawal 0x2aa
#define AcCmdCRGetItemFromStorage 0x29e
#define AcCmdCLGoodsShopList 0xb2
#define AcCmdCROpenRandomBox 0x43a
#define AcCmdCRGuildMemberList 0x2d6
#define AcCmdCRRequestGuildInfo 0x2e2
#define AcCmdCRModifyGuildEmblem 0x2e5
#define AcCmdCRWithdrawGuildMember 0x2c4
#define AcCmdCRUpdateGuildMemberGrade 0x2dc
#define AcCmdCRInviteGuildJoin 0x2cb
#define AcCmdCRCreateGuild 0x2be
#define AcCmdLCInviteGuildJoinOK 0x2d3
#define AcCmdLCInviteGuildJoinCancel 0x2d4
#define AcCmdCRStudyCareSkill 0x277
#define AcCmdCRResetCareSkill 0x27d
#define AcCmdCRChangeSkillCardPreset 0x236
#define AcCmdCLGetMessengerInfo 0x186
#define AcCmdCRRequestLeagueTeamList 0x37c
#define AcCmdCRPerformanceScore 0x1c8
#define AcCmdCRServerStats 0x306
#define AcCmdCRLog 0x11b
#define AcCmdCXSend 0x11e
#define AcCmdCXCast 0x11f
#define AcCmdCXEnterXRace 0x10d
#define AcCmdCRLeaveRanch 0x12f
#define AcCmdCLShowInventory 0x7e
#define AcCmdCRExpandMountSlot 0x26c
#define AcCmdCRRequestNpcDressList 0x44c
#define AcCmdUserRaceUpdatePos 0x103f
#define AcCmdUserRaceActivateEvent 0x10a0
#define AcCmdUserRaceActivateInteractiveEvent 0x10a1
#define AcCmdUserRaceDeactivateEvent 0x10a2
#define AcCmdCRTriggerEvent 0x1a4
#define AcCmdCRRelayCommand 0x2f5
#define AcCmdCRP2PResult 0x121
#define AcCmdCRRanchChat 0x137
#define AcCmdCRRemoveEquipment 0x84
#define AcCmdCRRevengeAssign 0x206
#define AcCmdCLEnterRoomQuick 0x95
#define AcCmdCRLeaveRoom 0x34
#define AcCmdCLQueryServerTime 0x26a
#define AcCmdCRRequestUserUid 0x454
#define AcCmdCLRequestFestivalPrize 0x1fc
#define AcCmdCRRestartRace 0x207
#define AcCmdCRConfirmSetItem 0x2b8
#define AcCmdCRBuyOwnItem 0x7b
#define AcCmdCRConfirmItem 0x2ad
#define AcCmdCRUpdateMountInfo 0x1cb
#define AcCmdCRSendGift 0x2a4
#define AcCmdCLMakeRoom 0x13
#define AcCmdCRRecoverMount 0x17d
#define AcCmdCRMountRentReset 0x32c
#define AcCmdCRStatusPointApply 0x153
#define AcCmdCLRequestMountInfo 0x275
#define AcCmdCRRegisterStallion 0x148
#define AcCmdCRCheckStallionCharge 0x1d5
#define AcCmdCRBreedingAbandon 0x15f
#define AcCmdCRChangeTeam 0x8a
#define AcCmdCLRequestFestivalResult 0x165
#define AcCmdCRBreedingTakeMoney 0x1f4
#define AcCmdCRUpdateMountNickname 0x197
#define AcCmdCLAchievementCompleteList 0xe5
#define AcCmdCLUpdateUserSettings 0x90
#define AcCmdCRUpdateBusyState 0x1a8
#define AcCmdCREnterRanch 0x12b
#define AcCmdCLRequestDailyQuestList 0x356
#define AcCmdCLRequestQuestList 0x3f8
#define AcCmdCLRequestSpecialEventList 0x417
#define AcCmdCLEnterRanchRandomly 0x109
#define AcCmdCLEnterRanch 0xfc
#define AcCmdCRMountGroupForce 0x219
#define AcCmdCLChangeRanchOption 0x30d
#define AcCmdCRKickRanch 0x45a
#define AcCmdCRRanchSnapshot 0x139
#define AcCmdCRWearEquipmentOK 0x82
#define AcCmdRCPetEffect 0x437
#define AcCmdCRTryBreedingCancel 0x158
#define AcCmdCREnterRanchCancel 0x12d
#define AcCmdCRLeaveRanchNotify 0x132
#define AcCmdCRRanchSnapshotNotify 0x13a
#define AcCmdCRRanchCmdActionNotify 0x1ca
#define AcCmdCRUpdateBusyStateNotify 0x1a9
#define AcCmdCRRanchStuffOK 0x1b0
#define AcCmdCRLeaveRanchOK 0x130
#define AcCmdCREnterBreedingMarketCancel 0x141
#define AcCmdCRSearchStallionCancel 0x147
#define AcCmdCRRegisterStallionOK 0x149
#define AcCmdCRRegisterStallionCancel 0x14a
#define AcCmdCRUnregisterStallionOK 0x14c
#define AcCmdCRUnregisterStallionCancel 0x14d
#define AcCmdCRUnregisterStallionEstimateInfoOK 0x297
#define AcCmdCRUnregisterStallionEstimateInfoCancel 0x298
#define AcCmdCRBreedingAbandonOK 0x160
#define AcCmdCRBreedingAbandonCancel 0x161
#define AcCmdCRBreedingWishlistCancel 0x1ea
#define AcCmdCRBreedingWishlistAddOK 0x1ec
#define AcCmdCRBreedingWishlistAddCancel 0x1ed
#define AcCmdCRBreedingWishlistDelOK 0x1ef
#define AcCmdCRBreedingWishlistDelCancel 0x1f0
#define AcCmdCRBreedingTakeMoneyOK 0x1f5
#define AcCmdCRBreedingTakeMoneyCancel 0x1f6
#define AcCmdCRCheckStallionChargeOK 0x1d6
#define AcCmdCRBreedingFailureCardOK 0x210
#define AcCmdCRBreedingFailureCardCancel 0x211
#define AcCmdCRBreedingFailureCardChooseCancel 0x214
#define AcCmdCRBuyOwnItemCancel 0x7d
#define AcCmdCROpenRandomBoxCancel 0x43c
#define AcCmdCRWearEquipmentCancel 0x83
#define AcCmdCRRemoveEquipmentOK 0x85
#define AcCmdCRRemoveEquipmentCancel 0x86
#define AcCmdCRUpdateMountInfoCancel 0x1cd
#define AcCmdCRRecoverMountOK 0x17e
#define AcCmdCRRecoverMountCancel 0x17f
#define AcCmdCRStatusPointApplyOK 0x154
#define AcCmdCRStatusPointApplyCancel 0x155
#define AcCmdCRUpdateMountNicknameCancel 0x199
#define AcCmdCRMountGroupForceOK 0x21a
#define AcCmdCRMountGroupForceCancel 0x21b
#define AcCmdCRAchievementBookRewardCancel 0x16e
#define AcCmdCRHousingBuildOK 0x25c
#define AcCmdCRHousingBuildCancel 0x25d
#define AcCmdCRHousingBuildNotify 0x25e
#define AcCmdCRHousingRepairOK 0x263
#define AcCmdCRHousingRepairCancel 0x264
#define AcCmdCRHousingRepairNotify 0x265
#define AcCmdCRExpandMountSlotOK 0x26d
#define AcCmdCRExpandMountSlotCancel 0x26e
#define AcCmdCRStudyCareSkillOK 0x278
#define AcCmdCRStudyCareSkillCancel 0x279
#define AcCmdCRResetCareSkillOK 0x27e
#define AcCmdCRResetCareSkillCancel 0x27f
#define AcCmdCRRequestStorageCancel 0x29b
#define AcCmdCRGetItemFromStorageCancel 0x2a0
#define AcCmdCRSendGiftCancel 0x2a6
#define AcCmdCRPurchaseWithdrawalOK 0x2ab
#define AcCmdCRPurchaseWithdrawalCancel 0x2ac
#define AcCmdCRConfirmSetItemOK 0x2b9
#define AcCmdCRConfirmSetItemCancel 0x2ba
#define AcCmdCRModifyGuildEmblemCancel 0x2e7
#define AcCmdCRChangeNicknameCancel 0x2fb
#define AcCmdCRMountRentInfoOK 0x323
#define AcCmdCRMountRentInfoCancel 0x324
#define AcCmdCRMountRentCancel 0x327
#define AcCmdCRMountRentResetOK 0x32d
#define AcCmdCRMountRentResetCancel 0x32e
#define AcCmdCRMountRentResetNotify 0x32f
#define AcCmdCRRequestDailyQuestRewardCancel 0x352
#define AcCmdCRRequestQuestRewardCancel 0x3f4
#define AcCmdCRRequestLeagueRewardCancel 0x384
#define AcCmdCRIncubateEggOK 0x3a0
#define AcCmdCRIncubateEggNotify 0x3a2
#define AcCmdCRBoostIncubateEggCancel 0x3ab
#define AcCmdCRBoostIncubateEggNotify 0x3ac
#define AcCmdCRBoostIncubateEggOtherCancel 0x3b0
#define AcCmdCRBoostIncubateEggOtherNotify 0x3b1
#define AcCmdCRAcceptBoostIncubateEggOK 0x3b8
#define AcCmdCRAcceptBoostIncubateEggCancel 0x3b9
#define AcCmdCRAcceptBoostIncubateEggNotify 0x3ba
#define AcCmdCRRequestPCBangGiftCancel 0x429
#define AcCmdCRCheckPCBangGiftItemOK 0x42e
#define AcCmdCRCheckPCBangGiftItemCancel 0x42f
#define AcCmdCRRideMountNotify 0x449
#define AcCmdCRRequestNpcDressListCancel 0x44e
#define AcCmdCRKickRanchOK 0x45b
#define AcCmdCRKickRanchCancel 0x45c
#define AcCmdRCKickRanchNotify 0x45d
#define AcCmdRCChangeAgeNotify 0x464
#define AcCmdRCHideAgeNotify 0x46b
#define AcCmdCRMountRent 0x325
#define AcCmdCRSendGiftOK 0x2a5
#define AcCmdCRMountRentOK 0x326
#define AcCmdCRMountRentNotify 0x32a
#define AcCmdCRPetBornResultNotify 0x3a5
#define AcCmdCRIncubateEggCancel 0x3a1
#define AcCmdCRRideGrazeMountNotify 0x44b
#define AcCmdCRTryBreedingOK 0x157
#define AcCmdCRAchievementBookRewardOK 0x16d
#define AcCmdCRModifyGuildEmblemOK 0x2e6
#define AcCmdCRBoostIncubateEggOK 0x3aa
#define AcCmdCRBoostIncubateEggOtherOK 0x3af
#define AcCmdCRUpdateMountNicknameOK 0x198
#define AcCmdCRConfirmItemOK 0x2ae
#define AcCmdCRConfirmItemCancel 0x2af
#define AcCmdCRChangeNicknameOK 0x2fa
#define AcCmdCRRequestUserUidOK 0x455
#define AcCmdCRRequestUserUidCancel 0x456
#define AcCmdCRUpdateMountInfoOK 0x1cc
#define AcCmdRCSetIntroductionNotify 0x174
#define AcCmdCRRanchChatNotify 0x138
#define AcCmdRCAddIdleMountInfoNotify 0x1e6
#define AcCmdCRBreedingFailureCardChooseOK 0x213
#define AcCmdCRBuyOwnItemOK 0x7c
#define AcCmdCROpenRandomBoxOK 0x43b
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_800 0x320
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_801 0x321
#define AcCmdCRRequestPetBirthOK 0x39b
#define AcCmdCRRequestPetBirthCancel 0x39c
#define AcCmdCRRequestPetBirthNotify 0x39d
#define AcCmdCRRequestNpcDressListOK 0x44d
#define AcCmdCREnterRanchNotify 0x12e
#define AcCmdCREnterBreedingMarketOK 0x140
#define AcCmdRCUpdatePetCancel 0x439
#define AcCmdCRGetItemFromStorageOK 0x29f
#define AcCmdCRRequestDailyQuestRewardOK 0x351
#define AcCmdCRRequestQuestRewardOK 0x3f3
#define AcCmdCRRequestLeagueRewardOK 0x383
#define AcCmdCRRequestPCBangGiftOK 0x428
#define AcCmdCRSearchStallionOK 0x146
#define AcCmdCRBreedingWishlistOK 0x1e9
#define AcCmdCREnterRanchOK 0x12c
#define AcCmdCRRequestStorageOK 0x29a
#define AcCmdCRBoostIncubateInfoListOK 0x3b6
#define AcCmdCLSetIntroduction 0x171
#define AcCmdCLRequestPersonalInfo 0xeb
#define AcCmdCRSetKeyAchievement 0x175
#define AcCmdCRAchievementDetail 0x244
#define AcCmdCRAchievementBookReward 0x16c
#define AcCmdCLUpdateSystemContent 0x1bd
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_793 0x319
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_799 0x31f
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumStringValueChanged_int_20_873 0x369
#define AcCmdCLClientNotify 0x309
#define AcCmdCRRequestSpur 0x99
#define AcCmdCRStartingRate 0xb0
#define AcCmdCRStarPointGet 0x9b
#define AcCmdCRHurdleClearResult 0xe7
#define AcCmdCRMountRentInfo 0x322
#define AcCmdCRRanchStuff 0x1af
#define AcCmdCRRequestUser 0x35e
#define AcCmdCRInviteUser 0x36d
#define AcCmdCRRanchCmdAction 0x1c9
#define AcCmdCRRanchCmdActionTo 0x453
#define AcCmdCRGameCreateClientItem 0x399
#define AcCmdCRRanchStuffStart 0x20d
#define AcCmdCRRanchStuffEnd 0x20e
#define AcCmdCRMountInjuryHeal 0x24b
#define AcCmdCRMobKnockback 0x424
#define AcCmdCRMobSkillToMob 0xd2
#define AcCmdCRMobSkillToMobHit 0xd8
#define AcCmdCRMobPlayerReflectSkill 0x112
#define AcCmdCLEnterRoomQuickStop 0x1f1
#elif ALICIA_PROTOCOL == 2
#define AcCmdCLPCInfoLog 0x412
#define AcCmdCRPlaceRanchDeco 0x4e9
#define AcCmdCRRemoveRanchDeco 0x4f1
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_726 0x2d6
#define AcCmdCLEnterRoomQuick 0x96
#define AcCmdCLLeaveParty 0x49d
#define AcCmdCLWithDrawPartyMember 0x48e
#define AcCmdCLCheckPartyReady 0x4a4
#define AcCmdCLEnterRoomQuickStop 0x1bc
#define AcCmdCLMakeParty 0x480
#define AcCmdCLEnterParty 0x496
#define AcCmdCLInviteParty 0x486
#define AcCmdCLUpdatePartyMemberState 0x4ab
#define AcCmdCLUpdatePartyChattingInfo 0x4c1
#define AcCmdCLGuildPartyList 0x368
#define AcCmdCLEnterGuildParty 0x36a
#define AcCmdCLStartGuildPartyMatch 0x376
#define AcCmdCLStopGuildPartyMatch 0x37c
#define AcCmdCLLeaveGuildParty 0x371
#define AcCmdCRRequestGuildMatchInfo 0x3ae
#define AcCmdCRRequestGuildRankingInfoList 0x3c6
#define AcCmdCLChangeGuildPartyOptions 0x3b6
#define AcCmdCLMakeGuildParty 0x362
#define AcCmdCRRequestGuildRankingInfo 0x3c3
#define AcCmdCRDeactivateSkillEffect 0xaa
#define AcCmdCRUseItem 0x1b4
#define AcCmdCRRideGrazeMount 0x3f0
#define AcCmdCRChangeMount 0x46e
#define AcCmdCRPasswordAuth 0x2ba
#define AcCmdCRUserPetInfos 0x388
#define AcCmdCRIncubateEgg 0x345
#define AcCmdCRBoostIncubateEgg 0x34f
#define AcCmdCRBoostIncubateInfoList 0x359
#define AcCmdCRBoostIncubateEggOther 0x354
#define AcCmdCRAcceptBoostIncubateEgg 0x35d
#define AcCmdCRPetBornResult 0x34a
#define AcCmdCRHousingBuild 0x218
#define AcCmdCRUpdatePet 0x336
#define AcCmdCRRequestPetBirth 0x340
#define AcCmdCRRegisterQuest 0x38c
#define AcCmdCRGiveupQuest 0x392
#define AcCmdCRRequestQuestReward 0x398
#define AcCmdCRChangeAge 0x404
#define AcCmdCRHideAge 0x40b
#define AcCmdCRRequestSystemParam 0x311
#define AcCmdCRRequestLeagueTeamList 0x325
#define AcCmdCLInquiryTreecash 0x26b
#define AcCmdCRTryBreeding2 0x504
#define AcCmdCRMixCards 0x4ce
#define AcCmdCRChangeNickname 0x2b3
#define AcCmdCLCreateNickname 0x6c
#define AcCmdCRCheckStorageItem 0x271
#define AcCmdCRPurchaseWithdrawal 0x264
#define AcCmdCRGetItemFromStorage 0x258
#define AcCmdCRAddAIPlayer 0x42a
#define AcCmdCRRemoveAIPlayer 0x42d
#define AcCmdCLGoodsShopList 0xb3
#define AcCmdCRBreedingRewardInfo 0x50a
#define AcCmdCRBreedingReward 0x50d
#define AcCmdCRMountFamilyTree 0x1db
#define AcCmdCRMountStorageList 0x51c
#define AcCmdCRGetMountFromStorage 0x51f
#define AcCmdCRUpdateMountNickname 0x173
#define AcCmdCRBreedingFoalInfo 0x513
#define AcCmdCRBreedingFoalBirth 0x516
#define AcCmdCRWearEquipmentMount 0x81
#define AcCmdCRWearEquipmentChar 0x45c
#define AcCmdCRRemoveEquipmentMount 0x84
#define AcCmdCRRemoveEquipmentChar 0x462
#define AcCmdCRChangeChar 0x468
#define AcCmdCRPutinSafebox 0x4d4
#define AcCmdCRReceiveLoginBonus 0x4fa
#define AcCmdCRUseGachaCoin 0x53d
#define AcCmdCLRequestPersonalInfo 0xec
#define AcCmdCRSetKeyEmblem 0x211
#define AcCmdCLSetIntroduction 0x14d
#define AcCmdCRRequestNewsboxList 0x4f7
#define AcCmdCRRequestStorage 0x253
#define AcCmdCRRemoveMountFromStorage 0x525
#define AcCmdCRUpdateMountInfo 0x1a7
#define AcCmdCRRequestSafeboxList 0x4e0
#define AcCmdCRTakeoutSafebox 0x4da
#define AcCmdCRAddSafeboxSlot 0x4e3
#define AcCmdCLRoomList 0x10
#define AcCmdCRPasswordAuthOK 0x2bb
#define AcCmdCRPasswordAuthCancel 0x2bc
#define AcCmdLCPartyStateNotify 0x4bf
#define AcCmdCLLoginCancel 0x9
#define AcCmdCLMakeRoomOK 0x14
#define AcCmdCLMakeRoomCancel 0x15
#define AcCmdCLEnterRoomOK 0x1d
#define AcCmdCLEnterRoomCancel 0x1e
#define AcCmdCLLeaveRoomOK 0x26
#define AcCmdLCLeavePartyRoom 0x4b9
#define AcCmdCLEnterChannelOK 0x2c
#define AcCmdCLEnterChannelCancel 0x2d
#define AcCmdCLLeaveChannelOK 0x2f
#define AcCmdCLDisconnectClientsNotify 0x14c
#define AcCmdCLCreateNicknameNotify 0x6b
#define AcCmdCLCreateNicknameCancel 0x6e
#define AcCmdCLShowInventoryCancel 0x80
#define AcCmdCLUpdateUserSettingsOK 0x92
#define AcCmdCLUpdateUserSettingsCancel 0x93
#define AcCmdCLEnterRoomQuickCancel 0x97
#define AcCmdCLGoodsShopListOK 0xb4
#define AcCmdCLGoodsShopListCancel 0xb5
#define AcCmdLCAchievementRewardNotify 0xef
#define AcCmdCLEnterRanchOK 0xfe
#define AcCmdCLEnterRanchCancel 0xff
#define AcCmdCLLeaveRanchOK 0x101
#define AcCmdCLLeaveRanchCancel 0x102
#define AcCmdLCMessengerCommandInvocation 0xe06
#define AcCmdLCGameguardCheckQuery 0x123
#define AcCmdLCGameguardEventNotify 0x125
#define AcCmdCLAchievementCompleteOK 0x144
#define AcCmdCLAchievementCompleteCancel 0x145
#define AcCmdCLGetMessengerInfoOK 0x163
#define AcCmdCLGetMessengerInfoCancel 0x164
#define AcCmdCLCheckWaitingSeqnoOK 0x198
#define AcCmdCLEnterRoomQuickStopOK 0x1bd
#define AcCmdCLEnterRoomQuickStopCancel 0x1be
#define AcCmdCLEnterRoomQuickSuccess 0x1c2
#define AcCmdCLEnterGuildPartyCancel 0x36c
#define AcCmdCLLeaveGuildPartyOK 0x372
#define AcCmdCLLeaveGuildPartyNotify 0x373
#define AcCmdCLStartGuildPartyMatchOK 0x377
#define AcCmdCLStartGuildPartyMatchCancel 0x378
#define AcCmdCLStopGuildPartyMatchOK 0x37d
#define AcCmdCLStopGuildPartyMatchCancel 0x37e
#define AcCmdLCGuildPartyMatchFound 0x383
#define AcCmdLCGuildMatchAvailable 0x3b5
#define AcCmdCLChangeGuildPartyOptionsCancel 0x3b8
#define AcCmdCLQueryServerTimeOK 0x228
#define AcCmdLCMissionRecordUpdate 0x108
#define AcCmdLCOpKick 0x24f
#define AcCmdLCHackShieldRequest 0x250
#define AcCmdLCHackShieldResult 0x252
#define AcCmdLCGoodsShopListData 0x26a
#define AcCmdCLInquiryTreecashOK 0x26c
#define AcCmdCLInquiryTreecashCancel 0x26d
#define AcCmdLCAlertGiftbox 0x257
#define AcCmdLCPTSPremiumInfo 0x2d1
#define AcCmdLCOpMute 0x2e5
#define AcCmdCLRequestLeagueInfoCancel 0x321
#define AcCmdCLCheckAccountDBAuthOK 0x16f
#define AcCmdCLCheckAccountDBAuthCancel 0x170
#define AcCmdCLEnterTownOK 0x414
#define AcCmdCLEnterTownCancel 0x415
#define AcCmdCLShowEggListCancel 0x433
#define AcCmdCLShowCharListCancel 0x4ca
#define AcCmdCLShowMountListCancel 0x43f
#define AcCmdCLRequestCharEquipmentListCancel 0x476
#define AcCmdCLRequestMountEquipmentListCancel 0x47c
#define AcCmdCLMakePartyCancel 0x482
#define AcCmdCLInvitePartyOK 0x487
#define AcCmdCLInvitePartyCancel 0x488
#define AcCmdCLEnterPartyCancel 0x498
#define AcCmdCLLeavePartyOK 0x49e
#define AcCmdCLLeavePartyCancel 0x49f
#define AcCmdLCLeavePartyNotify 0x4a0
#define AcCmdCLWithDrawPartyMemberOK 0x48f
#define AcCmdCLWithDrawPartyMemberCancel 0x490
#define AcCmdLCWithDrawPartyMember 0x495
#define AcCmdCLCheckPartyReadyOK 0x4a5
#define AcCmdCLCheckPartyReadyCancel 0x4a6
#define AcCmdLCCheckPartyReady 0x4aa
#define AcCmdCLUpdatePartyMemberStateOK 0x4ac
#define AcCmdCLUpdatePartyMemberStateCancel 0x4ad
#define AcCmdLCPartyMemberStateNotify 0x4b2
#define AcCmdLCPartyMemberScoreNotify 0x4b4
#define AcCmdLCMakeGuildParty 0x4bb
#define AcCmdLCLeaveGuildParty 0x4bd
#define AcCmdCLUpdatePartyChattingInfoOK 0x4c2
#define AcCmdCLUpdatePartyChattingInfoCancel 0x4c3
#define AcCmdLCUpdatePartyChattingInfoNotify 0x4c6
#define AcCmdCLRequestLicenseInfoCancel 0x52c
#define AcCmdCLHeartbeat 0x12
#define AcCmdCLCheckWaitingSeqno 0x197
#define AcCmdCLEnterChannel 0x2b
#define AcCmdCLLeaveChannel 0x2e
#define AcCmdCLLeaveRoom 0x25
#define AcCmdLCInvitePartyJoin 0x48d
#define AcCmdCLEnterRoom 0x1c
#define AcCmdLCEnterPartyRoom 0x4b6
#define AcCmdLCNotice 0x39
#define AcCmdCLEnterGuildPartyNotify 0x36d
#define AcCmdCLRequestDailyQuestListOK 0x300
#define AcCmdCLRequestQuestListOK 0x39f
#define AcCmdCLRequestSpecialEventListOK 0x3be
#define AcCmdLCEnterPartyNotify 0x499
#define AcCmdCLFeatureCommand 0x119
#define AcCmdCRAchievementUpdateProperty 0x147
#define AcCmdCLLogin 0x7
#define AcCmdCLAchievementCompleteListOK 0xe7
#define AcCmdLCUpdateSystemContent 0x19d
#define AcCmdCLChangeGuildPartyOptionsOK 0x3b7
#define AcCmdCLChangeGuildPartyOptionsNotify 0x3b9
#define AcCmdLCInviteGuildJoin 0x28c
#define AcCmdCLRequestMountInfoOK 0x233
#define AcCmdCLChangeRanchOptionOK 0x2c8
#define AcCmdCLChangeRanchOptionCancel 0x2c9
#define AcCmdCLRequestLeagueInfoOK 0x320
#define AcCmdCLShowCharListOK 0x4c9
#define AcCmdCLRequestCharEquipmentListOK 0x475
#define AcCmdCLRequestMountEquipmentListOK 0x47b
#define AcCmdCLRequestLicenseInfoOK 0x52b
#define AcCmdCLLoginOK 0x8
#define AcCmdCLShowInventoryOK 0x7f
#define AcCmdLCPersonalInfo 0xed
#define AcCmdCLShowEggListOK 0x432
#define AcCmdLCSkillCardPresetList 0x1f2
#define AcCmdCLEnterGuildPartyOK 0x36b
#define AcCmdCLRoomListOK 0x11
#define AcCmdCLShowMountListOK 0x43e
#define AcCmdCLMakePartyOK 0x481
#define AcCmdCLEnterPartyOK 0x497
#define AcCmdCLGuildPartyListOK 0x369
#define AcCmdRCLeaveRoom 0x2c5
#define AcCmdCRAddAIPlayerCancel 0x42c
#define AcCmdCRRemoveAIPlayerCancel 0x42f
#define AcCmdRCAddSkillEffect 0xa7
#define AcCmdRCMobMove 0xbf
#define AcCmdCRUpdateRanchLevelNotify 0x226
#define AcCmdCRRelay 0x2b1
#define AcCmdCRReadyRaceNotify 0x59
#define AcCmdCRStartRaceCancel 0x5c
#define AcCmdCRChangeMasterNotify 0x5d
#define AcCmdUserRaceTimerOK 0x1025
#define AcCmdBrokerTest 0x108e
#define AcCmdUserRaceCountdown 0x102d
#define AcCmdUserRaceDeleteNotify 0x1036
#define AcCmdGameRaceItemSpawn 0x1045
#define AcCmdGameRaceItemGet 0x1048
#define AcCmdGameQuestItemSpawn 0x104b
#define AcCmdGameQuestItemGet 0x104c
#define AcCmdUserRaceActivateEventNotify 0x10a0
#define AcCmdUserRaceActivateInteractiveEventNotify 0x10a1
#define AcCmdUserRaceDeactivateEventNotify 0x10a2
#define AcCmdUserRaceFinalNotify 0x1037
#define AcCmdCREnterRoomCancel 0x33
#define AcCmdCRLeaveRoomNotify 0x35
#define AcCmdCRLeaveRoomOK 0x36
#define AcCmdRCNPCSpawn 0x4a
#define AcCmdCRAttackNPCNotify 0x4c
#define AcCmdCRNPCAttachNotify 0x50
#define AcCmdRCNPCDestroyed 0x51
#define AcCmdCRKickNotify 0x5f
#define AcCmdCRChangeTeamOK 0x8b
#define AcCmdCRChangeTeamCancel 0x8c
#define AcCmdCRChangeTeamNotify 0x8d
#define AcCmdCRRequestItemOK 0x95
#define AcCmdCRRequestMagicItemOK 0xb7
#define AcCmdCRRequestMagicItemNotify 0xb8
#define AcCmdRCRagePointNotify 0x11d
#define AcCmdCRStarPointGetOK 0x9d
#define AcCmdCRUseItemSlotCancel 0xa5
#define AcCmdCRUseMagicItemCancel 0xbb
#define AcCmdRCRevengeTargetNotify 0x121
#define AcCmdRCRemoveSkillEffect 0xa8
#define AcCmdCRChangeUserSlotOK 0xac
#define AcCmdCRChangeUserSlotCancel 0xad
#define AcCmdCRChangeUserSlotNotify 0xae
#define AcCmdRCAddMonster 0xaf
#define AcCmdRCBindMonster 0xb0
#define AcCmdCRAttackMonsterNotify 0x64
#define AcCmdRCTeamSpurGauge 0xbd
#define AcCmdRCMobTrace 0xc0
#define AcCmdRCMobLookAt 0xc1
#define AcCmdRCMobSetScale 0xc2
#define AcCmdRCMobSetState 0xc3
#define AcCmdRCMobSetHP 0xc4
#define AcCmdRCMobDetachPart 0xc5
#define AcCmdRCMobSetMoveType 0xc6
#define AcCmdRCMobDead 0xc7
#define AcCmdRCMobUseSkillToGround 0xc8
#define AcCmdRCMobUseSkillToObject 0xc9
#define AcCmdRCMobMovingAttack 0x11b
#define AcCmdRCMobLead 0xcc
#define AcCmdRCMobSetHPBySkill 0xcd
#define AcCmdRCActivateLevelDevice 0xcf
#define AcCmdRCActivateLevelDeviceTrigger 0xd0
#define AcCmdRCDeactivateLevelDeviceTrigger 0xd1
#define AcCmdRCMobPlayerDamaged 0xd4
#define AcCmdRCMobPlayerSkillDamaged 0xd5
#define AcCmdRCMobEndGame 0xd6
#define AcCmdCRMobAttackMobNotify 0xd7
#define AcCmdCRMobSkillToMobNotify 0xd8
#define AcCmdRCMobPlayerStatus 0xdb
#define AcCmdRCMobPlayerSetHP 0xdc
#define AcCmdRCMobSetHPMax 0xde
#define AcCmdRCMobStop 0xdf
#define AcCmdRCMobResetPos 0xe0
#define AcCmdRCMissionEvent 0xe1
#define AcCmdRCLevelDeviceAction 0xeb
#define AcCmdRCCreateItem 0xe2
#define AcCmdRCMobKnockback 0xf2
#define AcCmdRCMobSetVelocity 0xf3
#define AcCmdRCCreateObstacle 0xf4
#define AcCmdRCMobAttachPart 0xf5
#define AcCmdRCMobRemoveStatus 0xf6
#define AcCmdRCMobTargetingOn 0xf7
#define AcCmdRCMobTargetingOff 0xf8
#define AcCmdRCMobUnlink 0xfa
#define AcCmdRCMobGazeAt 0xfb
#define AcCmdRCMobPlayerSetMP 0xfc
#define AcCmdRCMobPlayerDead 0x106
#define AcCmdRCMobRun 0x109
#define AcCmdRCMobThrust 0x10d
#define AcCmdRCMobPlayerReflectSkill 0xda
#define AcCmdRCMobSetDefaultState 0x118
#define AcCmdRCAlert 0x11e
#define AcCmdCRHurdleClearResultOK 0xe9
#define AcCmdCRRequestSpurOK 0x9b
#define AcCmdUserRaceCloseWait 0x1030
#define AcCmdRCAchievementCompleteNotify 0x158
#define AcCmdRCKickFromRace 0x161
#define AcCmdCRAwardEndNotify 0x191
#define AcCmdRCAwardNotify 0x171
#define AcCmdRCAwardEnd 0x172
#define AcCmdRCTriggerActivate 0x181
#define AcCmdCRTriggerizeAct 0x240
#define AcCmdCRLoadingCompleteNotify 0x193
#define AcCmdRCChangeAIOwner 0x1a3
#define AcCmdRCRoomCountdown 0x1b3
#define AcCmdCRRaceResultOK 0x1c8
#define AcCmdCRRaceResultCancel 0x1c9
#define AcCmdRCRoomCountdownCancel 0x1ca
#define AcCmdRCResetPos 0x1d3
#define AcCmdRCUpdateGameMoney 0x1f1
#define AcCmdCRMountFamilyTreeCancel 0x1dd
#define AcCmdRCGuildModeStar 0x1ff
#define AcCmdCRAchievementDetailCancel 0x203
#define AcCmdCRSetKeyAchievementOK 0x152
#define AcCmdCRSetKeyAchievementCancel 0x153
#define AcCmdCRMountInjuryHealOK 0x209
#define AcCmdCRMountInjuryHealCancel 0x20a
#define AcCmdCREmblemListCancel 0x210
#define AcCmdCRSetKeyEmblemOK 0x212
#define AcCmdCRSetKeyEmblemCancel 0x213
#define AcCmdCRSetKeyEmblemNotify 0x214
#define AcCmdRCAchievementUpdateNotify 0xe5
#define AcCmdCRCreateGuildOK 0x279
#define AcCmdCRCreateGuildCancel 0x27a
#define AcCmdCRWithdrawGuildMemberOK 0x27f
#define AcCmdCRWithdrawGuildMemberCancel 0x280
#define AcCmdCRGuildMemberListCancel 0x292
#define AcCmdCRUpdateGuildMemberGradeOK 0x297
#define AcCmdCRUpdateGuildMemberGradeCancel 0x298
#define AcCmdCRRequestGuildInfoCancel 0x29e
#define AcCmdRCWithdrawGuildMemberNotify 0x2a8
#define AcCmdRCUpdateGuildMemberGradeNotify 0x2aa
#define AcCmdRCModifyGuildEmblemNotify 0x2ae
#define AcCmdCRRelayCommandNotify 0x2b0
#define AcCmdCRUseItemOK 0x1b5
#define AcCmdCRUseItemCancel 0x1b6
#define AcCmdRCMagicExpire 0x2cd
#define AcCmdCRRegisterDailyQuestGroupOK 0x2e8
#define AcCmdCRRegisterDailyQuestGroupCancel 0x2e9
#define AcCmdCRUpdateDailyQuestOK 0x2ee
#define AcCmdCRUpdateDailyQuestCancel 0x2ef
#define AcCmdCRGiveupDailyQuestOK 0x2f4
#define AcCmdCRGiveupDailyQuestCancel 0x2f5
#define AcCmdRCUpdateDailyQuestNotify 0x305
#define AcCmdRCCompleteDailyQuestNotify 0x306
#define AcCmdCRRegisterQuestOK 0x38d
#define AcCmdCRRegisterQuestCancel 0x38e
#define AcCmdCRGiveupQuestOK 0x393
#define AcCmdCRGiveupQuestCancel 0x394
#define AcCmdRCUpdateQuestNotify 0x3a4
#define AcCmdRCUpdateLeagueScoreNotify 0x31b
#define AcCmdRCUpdateLeagueGradeNotify 0x31e
#define AcCmdCRRequestLeagueTeamListCancel 0x327
#define AcCmdRCGameCreateClientItem 0x33e
#define AcCmdRCObtainEgg 0x344
#define AcCmdRCGuildRaceInfo 0x3aa
#define AcCmdRCGuildRaceResult 0x3ac
#define AcCmdCRRequestGuildMatchInfoCancel 0x3b0
#define AcCmdCRRequestGuildRankingInfoCancel 0x3c5
#define AcCmdCRRequestGuildRankingInfoListCancel 0x3c8
#define AcCmdRCObstacleStatus 0x3f8
#define AcCmdCRChangeAgeOK 0x405
#define AcCmdCRChangeAgeCancel 0x406
#define AcCmdCRHideAgeOK 0x40c
#define AcCmdCRHideAgeCancel 0x40d
#define AcCmdCRAddAIPlayerOK 0x42b
#define AcCmdCRRemoveAIPlayerOK 0x42e
#define AcCmdRCAIPlayerAction 0x430
#define AcCmdRCUpdateLicenseInfo 0x532
#define AcCmdCRRecoverMountOK 0x15a
#define AcCmdCRRecoverMountCancel 0x15b
#define AcCmdCRChangeMagicTarget 0x1ea
#define AcCmdCRSkillSystemEvent 0x1f7
#define AcCmdCREnterRoom 0x30
#define AcCmdUserRaceTimer 0x1024
#define AcCmdCRHeartbeat 0x9f
#define AcCmdCRLoadingComplete 0x192
#define AcCmdCRTriggerLevelDevice 0xce
#define AcCmdUserRaceItemGet 0x10a3
#define AcCmdCRNPCAttach 0x4f
#define AcCmdCRKick 0x5e
#define AcCmdCRReadyRace 0x58
#define AcCmdCRChangeMagicTargetOK 0x1eb
#define AcCmdCRChangeMagicTargetCancel 0x1ec
#define AcCmdCRChangeMagicTargetNotify 0x1ed
#define AcCmdRCRemoveMagicTarget 0x1ee
#define AcCmdRCSkillSystemEvent 0x1fe
#define AcCmdCRAchievementDetailOK 0x202
#define AcCmdCRRelayNotify 0x2b2
#define AcCmdCRUseMagicItemOK 0xba
#define AcCmdCRUseMagicItemNotify 0xbc
#define AcCmdGameRaceClientUDPInfo 0x109d
#define AcCmdGameRaceP2PResult 0x109f
#define AcCmdCRUseItemSlotOK 0xa4
#define AcCmdCRUseItemSlotNotify 0xa6
#define AcCmdCRInviteGuildJoinCancel 0x286
#define AcCmdRCAcceptGuildJoinNotify 0x2ac
#define AcCmdCRAttackNPC 0x4b
#define AcCmdCRStartRace 0x5a
#define AcCmdCRChatNotify 0x53
#define AcCmdCRWhisperNotify 0x61
#define AcCmdRCMobAddMob 0xbe
#define AcCmdRCMobSetKey 0xca
#define AcCmdRCMobClearKey 0xcb
#define AcCmdRCUpdateMountInfoNotify 0x1bb
#define AcCmdCRServerStatsNotify 0x2c1
#define AcCmdCRRequestUserOK 0x308
#define AcCmdCRRequestUserCancel 0x309
#define AcCmdRCRequestUser 0x310
#define AcCmdCRInviteUserOK 0x317
#define AcCmdCRInviteUserCancel 0x318
#define AcCmdCRChat 0x52
#define AcCmdCRChangeRoomOptionsNotify 0x55
#define AcCmdCRUpdateEquipmentNotify 0x13d
#define AcCmdCROpCmdOK 0x24c
#define AcCmdRCMobLinkTo 0xf9
#define AcCmdRCDebugMessage 0x207
#define AcCmdCREmblemListOK 0x20f
#define AcCmdRCSupplyItemInsert 0x243
#define AcCmdCRRequestGuildInfoOK 0x29d
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_724 0x2d4
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_725 0x2d5
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_727 0x2d7
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_ePlayerConfig_11_728 0x2d8
#define AcCmdRCExchangeItem 0x33d
#define AcCmdRCUpdatePet 0x338
#define AcCmdCRRequestGuildMatchInfoOK 0x3af
#define AcCmdCRRequestGuildRankingInfoOK 0x3c4
#define AcCmdRCUpdateMountAppearanceNotify 0x1af
#define AcCmdRCResetItemWeekly 0x3dc
#define AcCmdCRChangeRoomOptions 0x54
#define AcCmdCREnterRoomNotify 0x31
#define AcCmdCRStartRaceNotify 0x5b
#define AcCmdRCUpdateSpecialEventNotify 0x3c2
#define AcCmdCRUpdateRaceBonusOK 0x501
#define AcCmdCRGuildMemberListOK 0x291
#define AcCmdCRRequestLeagueTeamListOK 0x326
#define AcCmdCREnterRoomOK 0x32
#define AcCmdCRMountFamilyTreeOK 0x1dc
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumStringValueChanged_int_20_787 0x313
#define AcCmdCRUserPetInfosOK 0x38b
#define AcCmdCRRequestGuildRankingInfoListOK 0x3c7
#define AcCmdRCRaceResultNotify 0x19f
#define AcCmdCLHackShieldResponse 0x251
#define AcCmdCRMountInjuryPlayEvent 0x200
#define AcCmdCREmblemList 0x20e
#define AcCmdCRChangeSkillCardPreset 0x1f3
#define AcCmdCRActivateSkillEffect 0xa9
#define AcCmdCRRequestMagicItem 0xb6
#define AcCmdCRAwardStart 0x179
#define AcCmdCRAwardEnd 0x157
#define AcCmdUserRaceFinal 0x1037
#define AcCmdCRRaceResult 0x69
#define AcCmdUserRaceP2PResult 0x109e
#define AcCmdCRMobActivateSkillEffect 0x3cb
#define AcCmdCRUseMagicItem 0xb9
#define AcCmdCRStartMagicTarget 0x1ef
#define AcCmdCROpCmd 0x24b
#define AcCmdCRMountCareCooltimeList 0x459
#define AcCmdCRCurrentMountInfo 0x533
#define AcCmdCRMountTraining 0x447
#define AcCmdCRMountFeed 0x44d
#define AcCmdCRMountPlaying 0x453
#define AcCmdCRCheckPCBangGiftItem 0x3d3
#define AcCmdCRRequestPCBangGift 0x3cd
#define AcCmdCRHousingRepair 0x21f
#define AcCmdCRGuildMemberList 0x290
#define AcCmdCRRequestGuildInfo 0x29c
#define AcCmdCRModifyGuildEmblem 0x29f
#define AcCmdCRWithdrawGuildMember 0x27e
#define AcCmdCRUpdateGuildMemberGrade 0x296
#define AcCmdCRInviteGuildJoin 0x285
#define AcCmdCRCreateGuild 0x278
#define AcCmdLCInviteGuildJoinOK 0x28d
#define AcCmdLCInviteGuildJoinCancel 0x28e
#define AcCmdCLGetMessengerInfo 0x162
#define AcCmdCROpenCardpack 0x537
#define AcCmdCLEnterTown 0x413
#define AcCmdCRLeaveTown 0x424
#define AcCmdCRUpdateBusyState 0x184
#define AcCmdCREnterTown 0x41c
#define AcCmdCLAchievementCompleteList 0xe6
#define AcCmdCLRequestQuestList 0x39e
#define AcCmdCLRequestSpecialEventList 0x3bd
#define AcCmdCRWearEquipmentMountOK 0x82
#define AcCmdCRWearEquipmentCharOK 0x45d
#define AcCmdRCPetEffect 0x3dd
#define AcCmdCREnterRanchCancel 0x12e
#define AcCmdCRLeaveRanchNotify 0x134
#define AcCmdCRRanchSnapshotNotify 0x13c
#define AcCmdCRRanchCmdActionNotify 0x1a6
#define AcCmdCRUpdateBusyStateNotify 0x185
#define AcCmdCRRanchStuffOK 0x18c
#define AcCmdCRLeaveRanchOK 0x132
#define AcCmdCRTryBreeding2OK 0x505
#define AcCmdCRTryBreeding2Cancel 0x506
#define AcCmdCRBreedingRewardInfoCancel 0x50c
#define AcCmdCRBreedingRewardOK 0x50e
#define AcCmdCRBreedingRewardCancel 0x50f
#define AcCmdCRBreedingFoalInfoOK 0x514
#define AcCmdCRBreedingFoalInfoCancel 0x515
#define AcCmdCRBreedingFoalBirthOK 0x517
#define AcCmdCRBreedingFoalBirthCancel 0x518
#define AcCmdCRMountStorageListCancel 0x51e
#define AcCmdCRGetMountFromStorageCancel 0x521
#define AcCmdCRRemoveMountFromStorageOK 0x526
#define AcCmdCRRemoveMountFromStorageCancel 0x527
#define AcCmdCRBreedingFailureCardOK 0x1ce
#define AcCmdCRBreedingFailureCardCancel 0x1cf
#define AcCmdCRBreedingFailureCardChooseCancel 0x1d2
#define AcCmdCRBuyOwnItemCancel 0x7d
#define AcCmdCROpenRandomBoxCancel 0x3e2
#define AcCmdCRWearEquipmentMountCancel 0x83
#define AcCmdCRRemoveEquipmentMountOK 0x85
#define AcCmdCRRemoveEquipmentMountCancel 0x86
#define AcCmdCRWearEquipmentCharCancel 0x45e
#define AcCmdCRRemoveEquipmentCharOK 0x463
#define AcCmdCRRemoveEquipmentCharCancel 0x464
#define AcCmdCRChangeCharOK 0x469
#define AcCmdCRChangeCharCancel 0x46a
#define AcCmdCRChangeMountOK 0x46f
#define AcCmdCRChangeMountCancel 0x470
#define AcCmdCRUpdateMountInfoCancel 0x1a9
#define AcCmdCRUpdateMountNicknameCancel 0x175
#define AcCmdCRAchievementBookRewardCancel 0x14a
#define AcCmdCRHousingBuildOK 0x219
#define AcCmdCRHousingBuildCancel 0x21a
#define AcCmdCRHousingBuildNotify 0x21b
#define AcCmdCRHousingRepairOK 0x220
#define AcCmdCRHousingRepairCancel 0x221
#define AcCmdCRHousingRepairNotify 0x222
#define AcCmdCRExpandMountSlotOK 0x22a
#define AcCmdCRExpandMountSlotCancel 0x22b
#define AcCmdCRStudyCareSkillOK 0x235
#define AcCmdCRStudyCareSkillCancel 0x236
#define AcCmdCRResetCareSkillOK 0x23b
#define AcCmdCRResetCareSkillCancel 0x23c
#define AcCmdCRRequestStorageCancel 0x255
#define AcCmdCRGetItemFromStorageCancel 0x25a
#define AcCmdCRSendGiftCancel 0x260
#define AcCmdCRPurchaseWithdrawalOK 0x265
#define AcCmdCRPurchaseWithdrawalCancel 0x266
#define AcCmdCRConfirmSetItemOK 0x273
#define AcCmdCRConfirmSetItemCancel 0x274
#define AcCmdCRModifyGuildEmblemCancel 0x2a1
#define AcCmdCRChangeNicknameCancel 0x2b5
#define AcCmdCRRequestDailyQuestRewardCancel 0x2fb
#define AcCmdCRRequestQuestRewardCancel 0x39a
#define AcCmdCRIncubateEggOK 0x346
#define AcCmdCRIncubateEggNotify 0x348
#define AcCmdCRBoostIncubateEggCancel 0x351
#define AcCmdCRBoostIncubateEggNotify 0x352
#define AcCmdCRBoostIncubateEggOtherCancel 0x356
#define AcCmdCRBoostIncubateEggOtherNotify 0x357
#define AcCmdCRAcceptBoostIncubateEggOK 0x35e
#define AcCmdCRAcceptBoostIncubateEggCancel 0x35f
#define AcCmdCRAcceptBoostIncubateEggNotify 0x360
#define AcCmdCRRequestPCBangGiftCancel 0x3cf
#define AcCmdCRCheckPCBangGiftItemOK 0x3d4
#define AcCmdCRCheckPCBangGiftItemCancel 0x3d5
#define AcCmdCRRideMountNotify 0x3ef
#define AcCmdCRRequestQuestEventInfoListCancel 0x3f4
#define AcCmdCRKickRanchOK 0x401
#define AcCmdCRKickRanchCancel 0x402
#define AcCmdRCKickRanchNotify 0x403
#define AcCmdRCChangeAgeNotify 0x40a
#define AcCmdRCHideAgeNotify 0x411
#define AcCmdCRMountTrainingCancel 0x449
#define AcCmdCRMountFeedCancel 0x44f
#define AcCmdCRMountPlayingCancel 0x455
#define AcCmdCRMountCareCooltimeListCancel 0x45b
#define AcCmdRCSocialActionNotify 0x500
#define AcCmdCRMixCardsCancel 0x4d0
#define AcCmdCRPutinSafeboxCancel 0x4d6
#define AcCmdCRTakeoutSafeboxCancel 0x4dc
#define AcCmdCRRequestSafeboxListCancel 0x4e2
#define AcCmdCRAddSafeboxSlotOK 0x4e4
#define AcCmdCRAddSafeboxSlotCancel 0x4e5
#define AcCmdCRRequestNewsboxListCancel 0x4f9
#define AcCmdCRReceiveLoginBonusCancel 0x4fc
#define AcCmdCRCurrentMountInfoCancel 0x535
#define AcCmdCROpenCardpackCancel 0x539
#define AcCmdCRUseGachaCoinCancel 0x53f
#define AcCmdCREnterTownCancel 0x41e
#define AcCmdCRLeaveTownNotify 0x427
#define AcCmdCRLeaveTownOK 0x425
#define AcCmdCRTownSnapshotNotify 0x429
#define AcCmdRCUpdateUserLevelNotify 0x90
#define AcCmdCRSendGiftOK 0x25f
#define AcCmdCRPetBornResultNotify 0x34b
#define AcCmdCRIncubateEggCancel 0x347
#define AcCmdCRRideGrazeMountNotify 0x3f1
#define AcCmdCRModifyGuildEmblemOK 0x2a0
#define AcCmdCRBoostIncubateEggOK 0x350
#define AcCmdCRBoostIncubateEggOtherOK 0x355
#define AcCmdCRPutinSafeboxOK 0x4d5
#define AcCmdCRTakeoutSafeboxOK 0x4db
#define AcCmdCRBreedingRewardInfoOK 0x50b
#define AcCmdCRUpdateMountNicknameOK 0x174
#define AcCmdCRConfirmItemOK 0x268
#define AcCmdCRConfirmItemCancel 0x269
#define AcCmdCRChangeNicknameOK 0x2b4
#define AcCmdCRRequestUserUidOK 0x3fb
#define AcCmdCRRequestUserUidCancel 0x3fc
#define AcCmdCREnterTownOK 0x41d
#define AcCmdRCAddIdleMountInfoNotify 0x1ba
#define AcCmdCRGetMountFromStorageOK 0x520
#define AcCmdCRUpdateMountInfoOK 0x1a8
#define AcCmdRCSetIntroductionNotify 0x150
#define AcCmdCRMountTrainingOK 0x448
#define AcCmdCRMountFeedOK 0x44e
#define AcCmdCRMountPlayingOK 0x454
#define AcCmdCRMountCareCooltimeListOK 0x45a
#define AcCmdCRCurrentMountInfoOK 0x534
#define AcCmdCRRanchChatNotify 0x13a
#define AcCmdCRBreedingFailureCardChooseOK 0x1d1
#define AcCmdCRBuyOwnItemOK 0x7c
#define AcCmdCROpenRandomBoxOK 0x3e1
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_730 0x2da
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_731 0x2db
#define AcCmdCRRequestPetBirthOK 0x341
#define AcCmdCRRequestPetBirthCancel 0x342
#define AcCmdCRRequestPetBirthNotify 0x343
#define AcCmdCREnterRanchNotify 0x12f
#define AcCmdRCUpdatePetCancel 0x3df
#define AcCmdRCRanchDecoList 0x4f0
#define AcCmdCRRequestNewsboxListOK 0x4f8
#define AcCmdCREnterTownNotify 0x41f
#define AcCmdCRAchievementBookRewardOK 0x149
#define AcCmdCRGetItemFromStorageOK 0x259
#define AcCmdCRRequestDailyQuestRewardOK 0x2fa
#define AcCmdCRRequestQuestRewardOK 0x399
#define AcCmdCRRequestPCBangGiftOK 0x3ce
#define AcCmdCRMixCardsOK 0x4cf
#define AcCmdCRRequestSafeboxListOK 0x4e1
#define AcCmdCRReceiveLoginBonusOK 0x4fb
#define AcCmdCROpenCardpackOK 0x538
#define AcCmdCRUseGachaCoinOK 0x53e
#define AcCmdCREnterRanchOK 0x12d
#define AcCmdCRMountStorageListOK 0x51d
#define AcCmdRCShowRanchVisitorInfo 0x130
#define AcCmdCRRequestStorageOK 0x254
#define AcCmdCRBoostIncubateInfoListOK 0x35c
#define AcCmdCRRequestQuestEventInfoListOK 0x3f3
#define AcCmdRCShowTownVisitorInfo 0x420
#define AcCmdCRPerformanceScore 0x1a4
#define AcCmdCRServerStats 0x2c0
#define AcCmdCRLog 0x11c
#define AcCmdCXSend 0x11f
#define AcCmdCXCast 0x120
#define AcCmdCXEnterXRace 0x10e
#define AcCmdCRLeaveRanch 0x131
#define AcCmdCLShowInventory 0x7e
#define AcCmdCLRequestLicenseInfo 0x52a
#define AcCmdCLRequestLeagueInfo 0x31f
#define AcCmdCLShowMountList 0x43d
#define AcCmdCLShowEggList 0x431
#define AcCmdCLShowCharList 0x4c8
#define AcCmdCLRequestCharEquipmentList 0x474
#define AcCmdCLRequestMountEquipmentList 0x47a
#define AcCmdCRRequestQuestEventInfoList 0x3f2
#define AcCmdUserRaceUpdatePos 0x103f
#define AcCmdUserRaceActivateEvent 0x10a0
#define AcCmdUserRaceActivateInteractiveEvent 0x10a1
#define AcCmdUserRaceDeactivateEvent 0x10a2
#define AcCmdCRTriggerEvent 0x180
#define AcCmdCRRelayCommand 0x2af
#define AcCmdCRP2PResult 0x122
#define AcCmdCRRanchChat 0x139
#define AcCmdCRRevengeAssign 0x1c4
#define AcCmdCRLeaveRoom 0x34
#define AcCmdCLQueryServerTime 0x227
#define AcCmdCRRequestUserUid 0x3fa
#define AcCmdCRRestartRace 0x1c5
#define AcCmdCRBuyOwnItem 0x7b
#define AcCmdCRConfirmItem 0x267
#define AcCmdCRSendGift 0x25e
#define AcCmdCLMakeRoom 0x13
#define AcCmdCRRecoverMount 0x159
#define AcCmdCLRequestMountInfo 0x232
#define AcCmdCRChangeTeam 0x8a
#define AcCmdCRMountInjuryHeal 0x208
#define AcCmdCLUpdateUserSettings 0x91
#define AcCmdCREnterRanch 0x12c
#define AcCmdCLEnterRanch 0xfd
#define AcCmdCLChangeRanchOption 0x2c7
#define AcCmdCRKickRanch 0x400
#define AcCmdCRTownSnapshot 0x428
#define AcCmdCRRanchSnapshot 0x13b
#define AcCmdCRPlaceRanchDecoCancel 0x4eb
#define AcCmdCRPlaceRanchDecoNotify 0x4ea
#define AcCmdCRRemoveRanchDecoCancel 0x4f3
#define AcCmdCRRemoveRanchDecoNotify 0x4f2
#define AcCmdCRSetKeyAchievement 0x151
#define AcCmdCRAchievementDetail 0x201
#define AcCmdCRAchievementBookReward 0x148
#define AcCmdCLUpdateSystemContent 0x199
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRaceConfig_5_723 0x2d3
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumValueChanged_enum_eRanchConfig_1_729 0x2d9
#define AcCmdUpdateEnumValueBase_class_AcDataByteListTemplate_struct_TEnumStringValueChanged_int_20_786 0x312
#define AcCmdCLClientNotify 0x2c3
#define AcCmdCRClientNotify 0x2c3
#define AcCmdCRRequestSpur 0x9a
#define AcCmdCRStartingRate 0xb1
#define AcCmdCRStarPointGet 0x9c
#define AcCmdCRHurdleClearResult 0xe8
#define AcCmdCRRanchStuff 0x18b
#define AcCmdCRRequestUser 0x307
#define AcCmdCRInviteUser 0x316
#define AcCmdCRRideMount 0x3ee
#define AcCmdCRRanchCmdAction 0x1a5
#define AcCmdCRRanchCmdActionTo 0x3f9
#define AcCmdCRGameCreateClientItem 0x33f
#define AcCmdCRRanchStuffStart 0x1cb
#define AcCmdCRRanchStuffEnd 0x1cc
#define AcCmdCRMobKnockback 0x3ca
#define AcCmdCRMobSkillToMob 0xd3
#define AcCmdCRMobSkillToMobHit 0xd9
#define AcCmdCRMobPlayerReflectSkill 0x113
#endif